version: 2.1

jobs:
  build-and-test:
    build:
      docker:
        # specify the version you desire here
        # use `-browsers` prefix for selenium tests, e.g. `3.8.7-browsers`
        - image: circleci/python:3.9.1
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python Happy AI.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
