version: 2.1

orbs:
  win: circleci/windows@2.2.0
  
jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: pip install -r requirements.txt
      - run: python Happy AI.py
    
workflow:
