version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - run: echo sans
      - run: pip install -r requirements.txt
      - run: python Happy AI.py

workflows:
  main:
    jobs:
      - build-and-test
